---
user:
  name: st0rmingbr4in
  group: st0rmingbr4in
  groups:
    - wheel
  shell: /bin/zsh
  home: /home/st0rmingbr4in
  password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34623633643634376266613436623939356335306438346631393835623935346161303064666238
          6639353638386238363263646533363366336131303533310a383235666365623038623138356333
          62616266313462643933646663646637663438663839303139656138663034323534636462643161
          3739366363643336380a373231343632383539623033303732353538623431383961346437353761
          37636663623164626665333364376634303366653363376538363937666438316462616532383266
          61633735326433333034653835306165613735363061313962303635356434646238643565653336
          35393436393734386364653433373765656638386438306331303831373266633366323263343035
          31373836363330363937616632303333653334363738633032646533623135373136313334396363
          32616332306631626230643931306539383933396433653335636464343038393232

git:
  name: "Julien DOCHE"
  email: julien.doche@gmail.com

wifi:
  interface: wlp4s0

  #TODO: enable dhcpcd on wired interface

gpu: nvidia

timezone:
  region: Europe
  city: Paris

ssh:
  port: 22
  enable_sshd: True
