---
- name: Install common dev tools
  pacman:
    update_cache: yes
    state: present
    name:
      - base-devel
      - bat
      - cmake
      - clang
      - gdb
      - git
      - opencl-headers
      - valgrind
      - yq
      - jq
      - hub
